import type { EventConfig, Template } from "./types";

/**
 * TEMPLATE: Cum Laude
 *
 * Kategori Wisuda — navy & emas, motif sertifikat (garis ganda, sudut
 * flourish), laurel wreath, medali/seal. Font Cinzel (serif klasik)
 * sengaja beda dari Playfair (Botanical) supaya kesan "formal akademik",
 * bukan "romantis".
 */

const event: EventConfig = {
  code: "CUMLAUDE",
  names: "CUM LAUDE",
  date: "20 Desember 2026",
  venue: "Aula Kampus",
  hashtag: "#CumLaude2026",
  quota: 250,
  brandLabel: "Selamat Wisuda",
  greeting:
    "Terima kasih sudah merayakan hari kelulusan ini bersama kami. Ambil foto sepuasnya, lalu titip pesan suara untuk kenangan.",
  voiceNoteEnabled: true,
  maxVoiceSeconds: 15,
  session: {
    countdownSeconds: 3,
    autoContinue: true,
    mirror: true,
    maxRetakes: 3,
    revealMs: 15000,
    filterCss: "brightness(1.04) contrast(1.08) saturate(1.05)",
    cameraAspect: "1:1",
    guestNameRequired: true,
    // Galeri "Momen" diunggah ke server (Vercel Blob di production / folder
    // lokal saat dev, lihat lib/moments.ts) — bersama lintas HP.
    moments: { enabled: true },
    share: {
      instagram: true,
      whatsapp: true,
      nativeShare: true,
      downloadPng: true,
      downloadJpg: true,
      downloadVideo: true,
    },
  },
  // Tema GELAP navy-emas — beda hue keluarga sepenuhnya dari Night Fest
  // (ungu-magenta neon): di sini gold/maroon formal, bukan neon.
  theme: {
    ink: "#0B1F3A",
    film: "#132A4D",
    edge: "#5C4A2A",
    smoke: "#B8A888",
    paper: "#F5EDE0",
    flash: "#D4AF37",
    live: "#B33A3A",
    brandPurple: "#7A1F2B",
    brandGold: "#D4AF37",
    fontDisplay: "var(--font-cinzel)",
    canvasFontDisplay: "var(--canvas-font-cinzel)",
    decorUrl: "/templates/cum-laude/decor-tl.png",
    videoBg: "/templates/cum-laude/bg-video.png",
    effects: {
      petals: { enabled: false, count: 0 },
      blobs: false,
      confetti: true,
      bokeh: false,
      sparkle: true,
    },
    elements: {
      monogram: { mode: "hidden" },
      buttonShape: "rounded",
      buttonStyle: "gradient",
      cardRadius: 8,
    },
  },
};

const frames: Template[] = [
  {
    id: "cum-laude-1",
    name: "Satu Foto Sertifikat",
    blurb: "Satu foto besar dengan bingkai garis emas ganda ala sertifikat, laurel & seal di bawah.",
    width: 900,
    height: 1600,
    printSize: "3 × 5.3\"",
    overlay: "/templates/cum-laude/CL1.png",
    paper: "#0B1F3A",
    slots: [{ x: 70, y: 140, w: 760, h: 1000 }],
    textLayers: [
      {
        text: "{{names}}",
        x: 450,
        y: 1330,
        size: 50,
        align: "center",
        color: "#D4AF37",
        face: "display",
        weight: 700,
        tracking: 3,
        uppercase: true,
        maxWidth: 720,
      },
      {
        text: "{{date}} · {{venue}}",
        x: 450,
        y: 1395,
        size: 22,
        align: "center",
        color: "#F5EDE0",
        face: "mono",
        maxWidth: 720,
      },
      {
        text: "{{hashtag}}",
        x: 450,
        y: 1440,
        size: 18,
        align: "center",
        color: "#D4AF37",
        face: "mono",
        weight: 700,
        tracking: 2,
        uppercase: true,
      },
    ],
  },
  {
    id: "cum-laude-2",
    name: "Tiga Foto Sertifikat",
    blurb: "Tiga jepretan berjajar, garis emas tipis dan topi toga di header.",
    width: 900,
    height: 1600,
    printSize: "3 × 5.3\"",
    overlay: "/templates/cum-laude/CL2.png",
    paper: "#132A4D",
    slots: [
      { x: 70, y: 180, w: 760, h: 380 },
      { x: 70, y: 580, w: 760, h: 380 },
      { x: 70, y: 980, w: 760, h: 380 },
    ],
    textLayers: [
      {
        text: "{{names}}",
        x: 450,
        y: 140,
        size: 32,
        align: "center",
        color: "#D4AF37",
        face: "display",
        weight: 700,
        tracking: 3,
        uppercase: true,
        maxWidth: 620,
      },
      {
        text: "{{date}}",
        x: 450,
        y: 1470,
        size: 24,
        align: "center",
        color: "#F5EDE0",
        face: "mono",
      },
      {
        text: "{{hashtag}}",
        x: 450,
        y: 1518,
        size: 18,
        align: "center",
        color: "#D4AF37",
        face: "mono",
        weight: 700,
        tracking: 2,
        uppercase: true,
      },
    ],
  },
  {
    id: "cum-laude-3",
    name: "Dua Foto Sertifikat",
    blurb: "Dua jepretan besar, garis emas tunggal dengan aksen bintang.",
    width: 900,
    height: 1600,
    printSize: "3 × 5.3\"",
    overlay: "/templates/cum-laude/CL3.png",
    paper: "#0B1F3A",
    slots: [
      { x: 70, y: 160, w: 760, h: 620 },
      { x: 70, y: 800, w: 760, h: 620 },
    ],
    textLayers: [
      {
        text: "{{names}}",
        x: 450,
        y: 100,
        size: 36,
        align: "center",
        color: "#F5EDE0",
        face: "display",
        weight: 700,
        tracking: 3,
        uppercase: true,
        maxWidth: 700,
      },
      {
        text: "{{venue}}",
        x: 450,
        y: 1500,
        size: 22,
        align: "center",
        color: "#F5EDE0",
        face: "mono",
        maxWidth: 700,
      },
      {
        text: "{{hashtag}}",
        x: 450,
        y: 1545,
        size: 16,
        align: "center",
        color: "#D4AF37",
        face: "mono",
        weight: 700,
        tracking: 2,
        uppercase: true,
      },
    ],
  },
];

export const cumLaude = {
  id: "cum-laude",
  label: "Cum Laude",
  blurb: "Navy & emas, motif sertifikat & laurel — cocok untuk wisuda. 3 bingkai.",
  event,
  frames,
};
